### ISSUE TITLE
Issue with bounding sensitivity

### ISSUE THREAD

**Issue by astorfi** [facebookresearch/pytorch-dp#11]
Hi,

I do want to address the problem of RDP calculation is the code. As I went through the paper [Renyi Differential Privacy of the Sampled Gaussian Mechanism](https://arxiv.org/pdf/1908.10530.pdf), the calculations are for l2-sensitivity of 1. 

In the code, there is a parameter defined as ``--sigma`` or ``noise_multiplier`` which will be [multiplied by the self.max_grad_norm](https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/privacy_engine.py#L91) and will be used to [calculate RDP](https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/privacy_engine.py#L73). The ``self.max_grad_norm`` limits the sensitivity of the function. However, the ``self.max_grad_norm`` parameter plays no part in the calculation of RDP. It is inconsistent with the [definitions of the main paper](https://arxiv.org/pdf/1908.10530.pdf).

Assume we increase the ``self.max_grad_norm`` value to a large number. Should we still get the same e-RDP guaranty? 

Also the $\sigma$ of the additive noise is ``self.noise_multiplier * self.max_grad_norm`` according to [this part of the code](https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/privacy_engine.py#L91) but it equals to self.noise_multiplier for calculation of the RDP as [implemented here](https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/privacy_analysis.py#L163-L179).

I think we should change the lines of [this part](https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/privacy_engine.py#L70-L76), to the following:
`     
def get_renyi_divergence(self):
        rdp = torch.tensor(
            tf_privacy.compute_rdp(
                self.sample_rate, self.noise_multiplier * self.max_grad_norm, 1, self.alphas
            )
        )
        return rdp
`

**Comment by ilyamironov** [comment]
Amirsina,

These are valid questions, and I'm glad to answer them.

Think about the additive Gaussian noise mechanism for computing the sum of reals. In its basic formulation we consider x_i from the range [0..1], compute their sum, and add noise sampled from N(0, sigma^2). It satisfies (alpha, alpha / 2*sigma^2)-RDP.

What if the numbers are coming from the range [0..B]? The analogue of the strategy employed in pytorch-dp is to add noise sampled from N(0, (B * sigma)^2). Crucially, the mechanism satisfies the same RDP guarantee. In other words, the privacy analysis is not dependent on B.

This is the reason why we refer to `sigma` as the noise **multiplier** and not the noise std.

Factoring the additive noise into the clipping-dependent part and the privacy-budgeting part makes sense to us because they play different roles and meet in code only once in the noise sampling parameter ("N(0, (B * sigma)^2)"). Does it address your concern?

--Ilya

**Comment by astorfi** [comment]
Thank you for your explanation. I understand your explanation and I agree. However, as I explained for the noise the sigma that is added is ``self.noise_multiplier * self.max_grad_norm`` which is aligned with your explanations. In the paper [Renyi Differential Privacy of the Sampled Gaussian Mechanism](https://arxiv.org/pdf/1908.10530.pdf) the sigma is still there and the sensitivity assumption is 1 as you mentioned.

So you are mentioning in RDP calculation, we should NOT use ``B * sigma`` as the noise sampling parameter and we should use ``sigma`` which defined as noise multiplier?

**Comment by ilyamironov** [comment]
> So you are mentioning in RDP calculation, we should NOT use B * sigma as the noise sampling parameter and we should use sigma which defined as noise multiplier?

That's right.

> My take from your explanation is that when self.max_grad_norm is higher than one, it suffices to add noise with std of self.noise_multiplier * self.max_grad_norm and calculate RDP with self.noise_multiplier as the previous state.

Agreed. Closing the issue.
